// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ITyPPpK0Ld3nNvRirRp_EKNFIg20KbE',
    appId: '1:589309487897:web:25b82c77271840bbf83388',
    messagingSenderId: '589309487897',
    projectId: 'mymuqabalaapp',
    authDomain: 'mymuqabalaapp.firebaseapp.com',
    storageBucket: 'mymuqabalaapp.firebasestorage.app',
    measurementId: 'G-NQ0KQ640GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoXIhI5W8T9vkUh2Q1kH0WUTt2LsKUGsI',
    appId: '1:589309487897:android:b7e6362c5a59bd51f83388',
    messagingSenderId: '589309487897',
    projectId: 'mymuqabalaapp',
    storageBucket: 'mymuqabalaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjjuTpds0Fkvcr1IpmOrgvXjq8-KfhHg4',
    appId: '1:589309487897:ios:07964ca78ec3df53f83388',
    messagingSenderId: '589309487897',
    projectId: 'mymuqabalaapp',
    storageBucket: 'mymuqabalaapp.firebasestorage.app',
    iosBundleId: 'com.mymuqabala.myMuqabala',
  );
}
